public class casestudies {

    public static void main(){
    /*
//current year
           		Integer year=Date.Today().year();
                system.debug('the current year is'+year);
    
//length of the variable
           		Integer result=s.length();
            	system.debug(result); 
       
//store loggedin user name
      			 string username= userinfo.getLocale();
        		 string user=userinfo.getUserName();
       			 system.debug(username user);
            
//start day of the week 
      			  date myDate = date.today();
        		  date weekStart = myDate.toStartofWeek();
        		  system.debug('start day'+weekStart); 

//store characters using string class    
      			  string username=userinfo.getLastName();
        		  string s=username.substring(0, 5);
        		  system.debug('store first 5 character'+s);*/
}
}