public class payslip 
{
    /*public static void details(string EmpName, string Phone, integer Empid, string email)
    {
       system.debug('Employee Name ='+EmpName);
        system.debug('Phone ='+Phone);
        system.debug('Employee id ='+Empid);
        system.debug('Email ='+email);
    }

	public static void arith(integer Cabfare, integer Homeallowance, integer salary)
{
 
    integer Overallsalary = Cabfare+Homeallowance+salary;
    system.debug('Overall Salary is'+Overallsalary);
}*/
    
    public static void datatype()
    {
       integer a= 30;
        long s= 2^60;
        double f= 3.423;
        Decimal r = 300000.59;
        date h = date.newInstance(2020, 09, 02);
        time j = time.newInstance(5, 9, 50, 20);
        id o = '0012w000007JBvAAAW';
        boolean b = true;
        boolean p = false;
        
      system.debug(a);
        system.debug(s);
        system.debug(f);
        system.debug(r);
        system.debug(h);
        system.debug(j);
       system.debug(o);
        system.debug(b);
        system.debug(p);
       
        
            
    }
       
    
}